src/Authentication.ResourceManager/AzureRmProfile.cs

Fix for https://github.com/Azure/azure-powershell/issues/7453

Fix issue with naming when no subscription is present in context

---

src/ScenarioTest.ResourceManager/AzureRM.Resources.ps1
src/ScenarioTest.ResourceManager/AzureRM.Storage.ps1

https://github.com/Azure/azure-powershell/issues/8124

Add aliases to common functions

---

src/ScenarioTest.ResourceManager/AzureRM.Resources.ps1

https://github.com/Azure/azure-powershell/issues/7990

Add functionality to AzureRm.Resources.ps1 script

---

src/Authentication.Abstractions/AzureEnvironmentConstants.cs

Fix issue https://github.com/Azure/azure-powershell/issues/7462 that reverts bug introduced in PR https://github.com/Azure/azure-powershell-common/pull/84

Fix bug in ADLS with endpoints

---

build/publish.proj

https://stackoverflow.com/a/38054505/294804

Add -UseBasicParsing so it doesn't fail with IE error

---

src/Network/Common/IVirtualNetwork.cs
src/Network/Common/IVirtualNetworkLinkVirtualNetwork.cs

Base interface for PSVirtualNetwork as this type is needed in PrivateDns VirtualNetworkLink module.

Add base interface for virtualnetwork ps class

---

src/Common/Extensions/CmdletExtensions.cs

For issue Azure/azure-powershell#8846 and PR Azure/azure-powershell#9051

Do not run AsJob with NoWait giving NoWait priority

---

src/Authentication.Abstractions/AzureEnvironment.cs
src/Authentication.Abstractions/AzureEnvironmentConstants.cs
src/Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs

add AzureAttestationServiceEndpointSuffix and AzureAttestationServiceEndpointResourceId for azure attestation service

add attestation service endpoint

---

Azure.PowerShell.Common.sln

Test build error in release mode so that remove them.

Remove Test in Release mode

---

src/Common/AzurePowerShell.cs

rollback change on src/Common/AzurePowerShell.cs

Rollback change and add ProductInfoHeaderValue for compatibility

---

src/Common/AzureRest/AzureRestClient.cs
src/Common/AzureRest/AzureRestOperations.cs
src/Common/AzureRest/IAzureRestClient.cs
src/Common/AzureRest/IAzureRestOperations.cs

* Change content from string to object
* Add deserialize settings
* Add Page support

Fix issues in AzureRestClient

---

src/Authentication.Abstractions.Test/AzureEnvironmentTests.cs
src/Authentication.Abstractions/AzureEnvironment.cs

Add default DNS endpoint
Add type of cloud environment 
Polish fallback logic

Support default DNS endpoint for env meta discovery

---

src/Graph.Rbac/Version1_6.20190326/ActiveDirectory/ActiveDirectoryClient.cs
src/Graph.Rbac/Version1_6/ActiveDirectory/ActiveDirectoryClient.cs

Fix the issue https://github.com/Azure/azure-powershell/issues/12192

Support searching ADUser by mail

---

src/Common/AzureDataCmdlet.cs
src/Common/AzurePSCmdlet.cs
src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs

* Move common attributes from AzureRmCmdlet to AzurePSCmdlet
* Add initial qosEvent in AzureDataCmdlet
* Change user agent format in client side telemetry
* Add AzVersion to user agent of HTTP request. (server telemetry)

Improve server and client telemetry

---

src/Storage/Adapters/ARM.Storage.Common.2019_06_01/ARMStorageProvider.cs
src/Storage/Adapters/ARM.Storage.Common.2019_06_01/ARMStorageService.cs

For https://github.com/Azure/azure-powershell/issues/13372

Add storage provider and service for storage management sdk 2019-06-01

---

src/Authentication.Abstractions/AzurePSErrorDataKeys.cs
src/Authentication.Abstractions/Interfaces/IContainsAzPSErrorData.cs
src/Common/MetricHelper.cs

* Add cloud error code which is fetched from CloudError
* Add new type of false error

Add cloud error code and new type of error

---

src/Common/Exceptions/AzPSApplicationException.cs
src/Common/Exceptions/AzPSArgumentException.cs
src/Common/Exceptions/AzPSArgumentNullException.cs
src/Common/Exceptions/AzPSArgumentOutOfRangeException.cs
src/Common/Exceptions/AzPSAuthenticationFailedException.cs
src/Common/Exceptions/AzPSCloudException.cs
src/Common/Exceptions/AzPSException.cs
src/Common/Exceptions/AzPSFileNotFoundException.cs
src/Common/Exceptions/AzPSIOException.cs
src/Common/Exceptions/AzPSInvalidOperationException.cs
src/Common/Exceptions/AzPSKeyNotFoundException.cs
src/Common/Exceptions/AzPSResourceNotFoundCloudException.cs

Add API description for Azure PowerShell exceptions.

Add API description for Azure PowerShell exceptions.

---

src/Common/AzurePSCmdlet.cs
src/Common/Properties/Resources.Designer.cs
src/Common/Properties/Resources.resx
src/Storage/Storage.nuspec

Two changes in this RP:
1. Display warning message that AzureRM will retire
2. Add missing pieces for  official 1.1.8 version

Display warning message that AzureRM will retire

---

NuGet.config
src/Common/Utilities/Base64UrlHelper.cs

...for keyvault to use.
Sample: https://github.com/Azure/azure-powershell/blob/56405b0dd1b9a889a71f732866dd476b0c88fc63/src/KeyVault/KeyVault/SecurityDomain/Models/JWK.cs#L99

Made `Base64UrlHelper.Encode(byte[])` public

---

src/Authentication.Abstractions/AzureEnvironment.cs
src/Authentication.Abstractions/HttpClientOperationsFactory.cs

This is to fix the issue https://github.com/Azure/azure-powershell/issues/14489

Async call in library should add ConfigureAwait(false)

---

src/Authentication.Abstractions/Extensions/AzureSubscriptionExtensions.cs

Related issue: https://github.com/Azure/azure-powershell/issues/15425

Fix access error when subscripiton has no Tags property

---

src/ResourceManager/Version2016_09_01/Generated/Models/Page.cs

Need deserialize nextLink from response.

Mapping nextLink to NextPageLink (#309)

---

src/Authentication.Abstractions/AzureEnvironment.cs
src/Authentication.Abstractions/AzureEnvironmentConstants.cs
src/Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs

Co-authored-by: Parv Saxena <pasaxena@microsoft.com>
Dataplane endpoints added.

Add purview endpoints for data plane auth (#303)

---

src/Dependencies.targets

Updated version of Azure.Core.dll to 1.24.0.0
Updated version of Azure.ResourceManager.dll to 1.1.1.0

Updated assembly version of Azure.Core.dll and Azure.ResourceManager.dll

---

src/Share/Survey/SurveyHelper.cs

Fix a key not found issue in survey in multi-process environment

---

src/Common/AzureRest/AzureRestOperations.cs

fix issue: https://github.com/Azure/azure-powershell/issues/18104

fix null reference in AzureRestOperation

---

NuGet.config

Replace MyGet feed with ADO packages.
Verified by https://dev.azure.com/azclitools/internal/_build/results?buildId=4607&view=results

Replace MyGet feed with ADO packages.

---

src/Authentication.Abstractions/AzureEnvironment.cs
src/Authentication.Abstractions/AzureEnvironmentConstants.cs
src/Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs

Add resource type id and suffix of App configuration

Add environment variables of App Configuration

---

src/Common/AzurePSCmdlet.cs
src/Common/MetricHelper.cs
src/Share/Survey/SurveyHelper.cs

1. Add Az.Accounts version in telemetry
2. Add env variable to show the whole telemetry
3. Revise intercept survey bug: prompt survey when the 3rd cmdlet runs.

Update telemetry to provide more info to survey

---

src/Authentication.Abstractions/Interfaces/IAzureSession.cs

Add KeyStoreFile to AzureSession Interface to fix https://github.com/Azure/azure-powershell-common/pull/363

Add KeyStoreFile to AzureSession Interface

---

src/Common/AzurePSCmdlet.cs
src/Common/IEndProcessingRecommendationService.cs
src/Common/MetricHelper.cs

Adds interface for the recommendation service. Will be implemented in the azure-powershell repo.

Interface for recommendation service

---

src/Authentication.Abstractions/AzureEnvironment.cs

Endpoints comparison between those before supporting new format and those with the current fix

Fix SynapseAnalyticsEndpointResourceId error

---

src/Authentication.Abstractions.Test/AzureEnvironmentTests.cs
src/Authentication.Abstractions.Test/TestData/ArmResponseWithEmptyGallery.json
src/Authentication.Abstractions/AzureEnvironment.cs

- Fix concurrent issue when Connect-AzAccount
- Add environment test for empty gallery endpoint

Fix concurrent issue when Connect-AzAccount

---

src/Authentication.Abstractions/AzureEnvironment.BuiltIn.cs
src/Authentication.Abstractions/AzureEnvironment.cs
src/Authentication.Abstractions/AzureEnvironmentConstants.cs
src/Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs

Added Communication Service Email endpoint

Added Communication Service Email endpoint

---

src/ResourceManager/Version2016_09_01/ArgumentCompleters/LocationCompleter.cs
src/ResourceManager/Version2016_09_01/ArgumentCompleters/ResourceGroupCompleter.cs
src/ResourceManager/Version2016_09_01/ArgumentCompleters/ResourceNameCompleter.cs
src/ResourceManager/Version2016_09_01/ArgumentCompleters/ResourceTypeCompleter.cs
src/ResourceManager/Version2016_09_01/ArgumentCompleters/ScopeCompleter.cs

Due to the rp count increasing. The response from ARM is much slower than before. We need to increase the timeout to 10s.

Update the timeout of argument completer to 10s
