Azure/azure-powershell-common

- src/ScenarioTest.ResourceManager/Common.ps1
Fixes: https://github.com/Azure/azure-powershell-common/issues/79
This allows `Get-Location` to return normalized location names when provided.
> Added UseCanonical switch for Get-Location

- src/TestFx/ITestRunner.cs
- src/TestFx/ITestRunnerFactory.cs
- src/TestFx/TestManager.cs
Zero guid replaced with dummy guid for the  tenantId to avoid wrong Azure env exception from KeyVault cmdlets. pre and post action params added to runScript method.
> Test controller update

- src/ScenarioTest.ResourceManager/Common.ps1
If `$resourceType` passed in `Get-Location` isn't found and `UseCanonical` is used, the function returns null instead of default location.
Since no resource type was found, `locations` array is `$null`. So when each element of `locations` is being normalized through `ForEach-Object` the following statement returns non-empty array: `$null | ForEach-Object`. Because of that, if-statement `$locations.Count -ne 0` is true and `$locations[0]` returns `@($null)[0]` i.e. `$null`
Example:
```
PS C:\> Get-Location "Microsoft.Network" "Usages" "westus"
West US
PS C:\> Get-Location "Microsoft.Network" "Usages" "westus" -UseCanonical
```
> Fix incorrect output of Get-Location when using UseCanonical

- src/Common/Properties/Resources.Designer.cs
- src/Common/Properties/Resources.resx
- src/ResourceManager/Properties/Resources.Designer.cs
- src/ResourceManager/Properties/Resources.resx
- src/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs
Updated usages of AzureRM.Profile to AzureRM.Accounts. The rename of AzureRM -> Az will be handled in the future across the entire repo. For now, we need `Profile` to say `Accounts` for tests to run in our module repo.
> 1: Change AzureRM.Profile to AzureRM.Accounts

- src/Aks/Aks.Netcore.csproj
- src/Aks/Aks.nuspec
- src/Aks/Properties/AssemblyInfo.cs
- src/Authorization/Authorization.Netcore.csproj
- src/Authorization/Authorization.nuspec
- src/Authorization/Properties/AssemblyInfo.cs
- src/Compute.Test/Compute.Test.Netcore.csproj
- src/Compute.Test/Properties/AssemblyInfo.cs
- src/Compute/Compute.Netcore.csproj
- src/Compute/Compute.nuspec
- src/Compute/Properties/AssemblyInfo.cs
- src/Graph.Rbac/Graph.Rbac.Netcore.csproj
- src/Graph.Rbac/Graph.Rbac.nuspec
- src/Graph.Rbac/Properties/AssemblyInfo.cs
- src/KeyVault/KeyVault.Netcore.csproj
- src/KeyVault/KeyVault.nuspec
- src/KeyVault/Properties/AssemblyInfo.cs
- src/Network/Network.Netcore.csproj
- src/Network/Network.nuspec
- src/Network/Properties/AssemblyInfo.cs
- src/ResourceManager/Properties/AssemblyInfo.cs
- src/ResourceManager/ResourceManager.Netcore.csproj
- src/ResourceManager/ResourceManager.nuspec
- src/Storage.Management/Properties/AssemblyInfo.cs
- src/Storage.Management/Storage.Management.Netcore.csproj
- src/Storage.Management/Storage.Management.nuspec
- src/Websites/Properties/AssemblyInfo.cs
- src/Websites/Websites.Netcore.csproj
- src/Websites/Websites.nuspec
This does the Common changes for https://github.com/Azure/azure-powershell/issues/7374.
Only changed the DLL names and package names for Clients. This does not include Storage (does include Storage.Management).
> 2: Rename Clients DLLs

- src/Authentication.Abstractions/Extensions/AzureSubscriptionExtensions.cs
The intent of `GetId` is to always return a Guid, even if it is just an empty Guid. This method throws if the `subscription` parameter is `null` (which is possible since it is an extension method). I added a `?` prior to attempting to access `Id` so the method evaluates correctly.
> Fixed GetId throwing on null IAzureSubscription

- src/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs
Changed `EnvironmentSetupHelper` to load modules from `artifacts/<CONFIG>` directory instead of `src/Package/<CONFIG>/ResourceManager/AzureResourceManager`
> Allow test modules to load from artifacts directory

- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
I also validated that they all resolve to the same resource.
> Change http to https URLs.

- src/Authentication.Abstractions/AzureEnvironment.cs
- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
- src/Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs
- src/Authentication.Abstractions/Interfaces/IAzureEnvironment.cs
Reverts Azure/azure-powershell-common#156
This PR updates the IAzureEnvironment interface in our base abstractions.  This is a binary breaking change that will cause issues with any version of a module depennding on the previous abstraction.
When we add new endpoints, we add them in the Extensions dictionary, not to the interface itself, like this: https://github.com/Azure/azure-powershell-common/blob/master/src/Authentication.Abstractions/AzureEnvironment.cs#L56
We should have noticed the problem earlier. Sorry for the inconvenience @shleiAmy , please re-submit your PR.
cc @markcowl
> Revert "add attestation endpoint and token audience required for authenticating with Azure Attestation tenants"

- src/Common/AzurePSCmdlet.cs
Fix the issue https://github.com/Azure/azure-powershell/issues/8963
Enable warning messages printout in module importing.
>  Disable context auto saving when AzureRmContext.json not available

- src/Common/AzurePSCmdlet.cs
- src/Common/AzurePowerShell.cs
- src/Common/MetricHelper.cs
- src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
Changes around customer data in client telemetry:
1. Fetch and add az version to user agent
2. Add start time, end time, and effective execution duration
3. Add AZUREPS_HOST_ENVIRONMENT to user agent
4. Add subscription id and tenant id
A minor change is to remove exception message if cmdlet has no exception.
Another minor change is fixing issue https://github.com/Azure/azure-powershell/issues/10887
> Add az version, time, and subscription id to client telemetry

- src/Common/AzurePSCmdlet.cs
Remove Az version fetching logic due to solution has flaw:
- Get-InstalledModule has performance problem which takes about 10 seconds.
- Get-Module cannot get version on Windows PowerShell and its version doesn't have version label.
> Remove Az version fetching logic due to solution has flaw.

- src/Common/AzurePSCmdlet.cs
Fi xes https://github.com/Azure/azure-powershell/issues/11492
> Change the way we call powershell in AzurePSCmdlet

- src/Common/AzurePSCmdlet.cs
- src/Common/Common.csproj
- src/Common/MetricHelper.cs
This reverts commit 0bfa2f3f6e015ea9492b2e33b427adb0de2f76f7. because OOM issue is found when we use ApplicationInsight SDK 2.12.0. We need to upgrade it later once issue is resolved.
> Revert "Upgrade application insight SDK version to 2.12.0 (#189) (#190)"

- src/Common/AzurePSCmdlet.cs
Get module name from assembly is incorrect for binary cmdlet. It should be fetched from MyInvocation properties.
Adjust cmdlet name fetch logic together
> Add correct module name and version from MyInvocation

- src/Authentication.Abstractions.Test/Authentication.Abstractions.Test.csproj
- src/Authentication.Abstractions.Test/AzureEnvironmentTests.cs
- src/Authentication.Abstractions.Test/TestData/ArmResponse2019-05-01.json
- src/Authentication.Abstractions/AzureEnvironment.cs
SqlDatabaseDnsSuffix needs to lead with period character
ServiceManagementUrl needs to end with slash
ARM team cannot change their payload because it may impact other clients. Above logic is added when AzureEnvironment is imported from discovery endpoint.
> Adjust value from ARM endpoint due to compatibility

- src/Authentication.Abstractions.Test/AzureEnvironmentTests.cs
- src/Authentication.Abstractions.Test/TestData/ArmResponseNoAzureCloud.json
- src/Authentication.Abstractions.Test/TestData/ArmResponseOneEntry.json
- src/Authentication.Abstractions/AzureEnvironment.cs
Fix for this issue
https://github.com/Azure/azure-powershell/issues/12633
> Merge built-in environments and discovered environemnts

- src/Common/CustomAttributes/BreakingChangeAttributeHelper.cs
- src/Common/CustomAttributes/CmdletParameterBreakingChangeAttribute.cs
- src/Common/CustomAttributes/GenericBreakingChangeAttribute.cs
- src/Common/Properties/Resources.resx
This PR is related to https://github.com/Azure/azure-powershell/pull/12740
> Format BreakingChange Output Messages in Common Repo

- src/Authentication.Abstractions/AzureEnvironment.cs
- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
- src/Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs
Sign build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=531191&view=results
> Add endpoints for managed HSM

- src/Authentication.Abstractions/DiskDataStore.cs
- src/Authentication.Abstractions/Properties/AssemblyInfo.cs
- src/Common/Properties/AssemblyInfo.cs
- src/ServiceManagement/Properties/AssemblyInfo.cs
- src/ServiceManagement/PublishSettingsImporter.cs
Dotnet had a bug that did not remove temporary private keys (non-persistent) for certificates. September Rollup fixed this bug. As the result, client is blocked because private keys are removed during importing publish setting because its code uses default key setting. The correct way is we should set PersistKeySet explicitly
Details is from https://docs.microsoft.com/en-us/troubleshoot/dotnet/framework/install-pfx-file-using-x509certificate
> Set X509KeyStorageFlags.PersistKeySet flag explicitly

- src/Authentication.Abstractions/Interfaces/IContainsAzPSErrorData.cs
- src/Common/MetricHelper.cs
Couple improvements
* The value being set into exception.data should explicitly parse to string on .NET Framework.
* Shorten exception and just show its message during debug mode
The issue is https://github.com/Azure/azure-powershell/issues/14556
> Improve exception message in telemetry

- src/Authentication.Abstractions/AzureEnvironment.cs
If ResourceID is not provided by ARM endpoint, we assume it is consistent with DNS suffix.
> Use DNS suffix as resource id when it is not provided

- src/Authentication.Abstractions/AzureEnvironment.cs
- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
OperationalInsights supports ChinaCloud now. Add endpoint to built-in environment.
> Add endpoint of OperationalInsights in ChinaCloud

- src/Authentication.Abstractions/AzureEnvironment.cs
- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
Fixed 2 typos in AzureEnvironment and AzureEnvironmentConstants
(no need for a new common build)
> Fixed typo in environement contants

- src/Common/AzurePSCmdlet.cs
- src/Common/Common.csproj
- src/Common/MetricHelper.cs
- Upgrade Microsoft.ApplicationInsights from 2.4.0 to 2.12.0
> Upgrade Microsoft.ApplicationInsights from 2.4.0 to 2.12.0

- src/Common/AzurePSCmdlet.cs
- src/Common/MetricHelper.cs
PSVersion previously is fetch via $Host.Version. After discussion with PowerShell team, the correct way is $Host.Runspace.Version. So, it changes below codes:
* Get correct PowerShell version via `$Host.Runspace.Version` in PowerShell scripts
* Keep host name and version into new telemetry properties
* Add additional information into telemetry debug message
* Clean deprecated code.
> Get correct PSVersion from PowerShell runtime

- src/Common/AzurePSCmdlet.cs
- src/Common/MetricHelper.cs
Fix one issue in https://github.com/Azure/azure-powershell-common/pull/278
ToString() in `$Host.Runspace.Version.ToString()` leads script error when PowerShell runspace has no version.
> Fix script of getting PowerShell version

- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
- Fix the issue in https://github.com/Azure/azure-powershell/issues/15429
- Refer to the https://azure.microsoft.com/en-us/account/ for the official portal link (https://management.azure.com/metadata/endpoints?api-version=2019-05-01)
> Fix the management portal url

- src/Authentication.Abstractions.Test/ContextUnitTests.cs
- src/Authentication.Abstractions/Extensions/AzureContextExtensions.cs
- src/Authentication.Abstractions/Interfaces/IAzureContextContainer.cs
- src/Common/Attributes/SupportsSubscriptionId.cs
- src/ResourceManager.Test/AzureRMCmdletUnitTests.cs
- src/ResourceManager/Properties/Resources.Designer.cs
- src/ResourceManager/Properties/Resources.resx
- src/ResourceManager/ResourceManager.csproj
- src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
autorest-based modules support `-Subscription` parameter to operate on non-default subscription, but there's no universal way to enable it for sdk-based ones.
A `SupportsSubscriptionId` attribute is introduced. When applied to a cmdlet (or a cmdlet base class), the cmdlet(s) will have a `-SubscriptionId` parameter, implemented by `IDynamicParameter`. And during its lifecycle, the default profile and context will be cloned, the subscription will be replaced by what user specifies. Therefore when creeating SDK client or sending request, the input subscription ID will be used.
> Enable custom subscription ID by attribute

- src/Authentication.Abstractions/Interfaces/IAzureContextContainer.cs
- src/Common/Utilities/ISharedUtilities.cs
- src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
Adding APIs to well-known types (`IAzureContextContainer` in this case) is risky as:
- It is a binary breaking change - what if someone implements the interface in their own code
- It is harder not to introduce breaking change the bigger the interface grows.
So, we came up with a pattern to avoid touching `IAzureContextContainer`, using `ComponentRegistery`.
Related powershell PR: https://github.com/Azure/azure-powershell/pull/15743
> Undo adding new API to IAzureContextContainer

- src/Common/AzurePSCmdlet.cs
For https://github.com/Azure/azure-powershell/issues/16291
Fetch module name and module version in  `BeginProcessing()` instead of `InitializeQosEvent()` because those 2 information are required by telemetry and useragent both.
Currently, we append 3 product information into useragent, AzurePowerShell, PowerShell, and module now. Azure PowerShell and PowerShell are constant in one PowerShell process but module information needs to be removed after cmdlet execution. But remove method `AzureSession.Instance.ClientFactory.RemoveUserAgent(ModuleName);` is not safe when cmdlet execution is cancelled. It will be addressed in `azure-powershell\src\Accounts\Authentication\Factories\ClientFactory.cs`
> Add module version to useragent

- .azure-pipelines/Azure-PowerShell-Common-Publish.yml
Update the vm image of pipeline [azure-powershell-common sign & publish](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=2436&nonce=HmQHyxzMgBiMb22MoZJGOg%3D%3D) to windows-2019
Issue: https://github.com/Azure/azure-powershell/issues/16275
> Update build image to windows-2019

- src/Common/AzurePSCmdlet.cs
- src/Common/MetricHelper.cs
- Add property SessionId, which is used to identify a PowerShell Process
- Add thread level property TelemetryId, which is used to identify a telemetry
- Add thread level property InternalCalledCmdlets, which keeps the internal called cmdlets
> Update common lib for telemetry improvement

- src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
Provide a little extra information in logs (debug, warning and verbose).
Before vs. After. Note the fifth line.
> Write log with timestamps

- src/Dependencies.targets
Just upgrade the version of Microsoft.Rest.ClientRuntime.Azure. We don't need to release a new version only for this change.
> Upgrade the version of Microsoft.Rest.ClientRuntime.Azure

- src/Common/MetricHelper.cs
The root cause of the issue is as listed in [here](https://docs.microsoft.com/en-us/dotnet/api/system.threadstaticattribute?redirectedfrom=MSDN&view=net-6.0). 
`Initialization occurs only once, when the class constructor executes, and therefore affects only one thread.`
> Fixed a telemtry related issue in multi-thread

- src/Common/Utilities/GeneralUtilities.cs
Changed default cancellation token from "default" to "CancellationToken.None" as C# 7.0 does not support it
> Changed default cancellation token

- src/Authentication.Abstractions.Test/AzureEnvironmentTests.cs
- src/Authentication.Abstractions.Test/TestData/ArmResponseNoAzureCloud.json
- src/Authentication.Abstractions/AzureEnvironment.cs
- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
- src/Authentication.Abstractions/EnvironmentName.cs
According to announcement https://www.microsoft.com/en-us/cloud-platform/germany-cloud-regions, this pull request removes German Cloud from environment list. Related public variables have added obsolete attribute.
> Deprecate Azure German Cloud

- src/Common/MetricHelper.cs
Fixed the issue in the Release build where EnableTestCoverage flag is not registered. The release build also does not have ITestCoverage component registered. Move this condition ahead of EnableTestCoverage flag to short-circuit the if logic.
> Fixed issue when EnableTestCoverage was not registered

- src/Common/AzurePSCmdlet.cs
Currently, we use $Host.runspace.version for PowerShell version. It is the PowerShell engine version, and should be same as the $psversiontable.psversion, but runspace will be null in some cases for example when developers directly use PowerShell SDK as below.
```
```
> Use $PSVersionTable.PSVersion for PowerShell Version

- src/Authentication.Abstractions.Test/AzureEnvironmentTests.cs
- src/Authentication.Abstractions.Test/TestData/ArmResponse2022-09-01.json
- src/Authentication.Abstractions/AzureEnvironment.BuiltIn.cs
- src/Authentication.Abstractions/AzureEnvironment.cs
- src/Authentication.Abstractions/AzureEnvironmentBuiltInSettings.cs
- src/Authentication.Abstractions/Models/ArmMetadata.cs
- src/Authentication.Abstractions/Models/SuffixEndpoints.cs
ArmMetadata with API version 2022-09-01 has changed the response format from array to single object. Also properties in the metadata are also changed.
- Update the related code to support new format of metadata
- Use the properties in the metadata to update the endpoints of MicrosoftGraph, Attestation and SynapseAnalytics endpoints
- Fix the target framework issue of test projects
> Support ArmMetadata with API version 2022-09-01

- src/Common/AzurePSCmdlet.cs
- src/Common/Telemetry/IParameterTelemetryFormatter.cs
This PR contains the interface definition for an utility to format PSBoundParameters (including names and values) to a string. The string will be included in the client-side telemetry.
> Interface for collection parameter values

- src/Authentication.Abstractions/AzureEnvironment.cs
DefaultArmMetaDataEndpoint assignment is removed in https://github.com/Azure/azure-powershell-common/pull/374
Revert the incorrect change in https://github.com/Azure/azure-powershell-common/pull/374
> Missing DefaultArmMetaDataEndpoint assignment

- src/Authentication.Abstractions/AzureEnvironment.BuiltIn.cs
Change the current wrong endpoint `https://region.asazure.usgovcloudapi.net` to `https://dev.azuresynapse.usgovcloudapi.net`
Test: https://github.com/Azure/azure-powershell/pull/21516
> Fix the incorrect AzureSynapseAnalyticsEndpointResourceId of USGovernment

- src/Common/AzurePSCmdlet.cs
- src/Common/Common.csproj
- src/Common/CustomAttributes/CmdletPreviewAttribute.cs
- src/Common/CustomAttributes/GenericBreakingChangeAttribute.cs
- src/Common/CustomAttributes/GenericBreakingChangeWithVersionAttribute.cs
- src/Common/CustomAttributes/PreviewAttributeHelper.cs
- src/Common/Properties/Resources.Designer.cs
- src/Common/Properties/Resources.resx
> Change the default warning message of CmdletPreviewAttribute and allow setting ETA

- src/Aks/Aks.csproj
- src/Authorization/Authorization.csproj
- src/Common/Common.csproj
- src/Common/Properties/Resources.Designer.cs
- src/Network/Network.csproj
The access level of Resources.Designer.cs is decided by the custom tool of Resources.resx.
ResXFileCodeGenerator means internal access and PublicResXFileCodeGenerator means public access.
In our code, ResXFileCodeGenerator is used as the custom tool of Resources.resx files. But part of Resources.Designer.cs files is internal access and remaining is public access.
**Adjusted the custom tool to PublicResXFileCodeGenerator or ResXFileCodeGenerator to keep consistent behavior in this PR.**
Note that the access level of some Resources.Designer.cs files are internal, this PR doesn't change their custom tool.
> Fixed bug about access level in Resources.Designer.cs

- src/Common/CustomAttributes/BreakingChangeAttributeHelper.cs
- src/Common/CustomAttributes/GenericBreakingChangeWithVersionAttribute.cs
- src/Common/Properties/Resources.Designer.cs
- src/Common/Properties/Resources.resx
This PR will add module name to breaking change message.
The message is updated from 
`The change is expected to take effect from version : '<module version>'` 
to 
`The change is expected to take effect from <module name> version : '<module version>'`
Before this change, the breaking change message looks like
```powershell
PS /> Get-AzPolicyDefinition -Name ******
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzPolicyDefinition' :
- The output type 'Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Policy.PsPolicyDefinition' is changing
- The following properties in the output type are being deprecated : 'Properties'
- The following properties are being added to the output type : 'Description' 'DisplayName' 'Metadata' 'Mode' 'Parameters' 'PolicyRule' 'PolicyType'
- …
```
> Add module name to breaking changes

- src/Common/CustomAttributes/BreakingChangeAttributeHelper.cs
get breaking change attribute for all parameters instead of runtime properties only, in this way breaking change attribute for dynamic parameters are able to be displayed
> support breaking change attribute for dynamic parameters

- src/ResourceManager.Test/AzureRMCmdletAuthenticationUnitTests.cs
- src/ResourceManager.Test/MockAccessToken.cs
- src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
This pull request includes changes to add new unit tests and methods related to authentication functionality. The most important changes include adding a new unit test class `AzureRMCmdletAuthenticationUnitTests` with test methods for the `GetAuxilaryAuthHeaderByTenatIds` method, and adding a new method `GetAuxiliaryAuthHeaderFromTenantIds` to the `AzureRMCmdlet` class for generating authentication headers.
Authentication improvements:
* [`src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs`](diffhunk://#diff-4fc6524a8cc5579c0ba48a332feff18740fd36a7976cf50ff058859f316044b2R150-R174): Added a new method `GetAuxiliaryAuthHeaderFromTenantIds` to the `AzureRMCmdlet` class for generating authentication headers for a list of tenant IDs.
Testing improvements:
* …
> Enable TenantId to Retrieve Auxiliary Auth Header

- src/Common/AzurePSCmdlet.cs
- src/Common/ColorAndFormat/PSStyle.cs
- src/Common/Properties/Resources.Designer.cs
- src/Common/Properties/Resources.resx
- src/Dependencies.targets
- src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
- Added method to write information and write string information.
- Predefined ansi color and format used in device code login message.
> Add WriteInformation Method in AzurePSCmdlet

- src/Common/AzurePSCmdlet.cs
- src/Common/MetricHelper.cs
This pull request includes changes in two files: `src/Common/AzurePSCmdlet.cs` and `src/Common/MetricHelper.cs`. The changes revolve around the handling and logging of sanitizer information. The debug log about the sanitizing process duration has been removed from `AzurePSCmdlet.cs`. In `MetricHelper.cs`, the `ToString()` method has been updated to include the sanitizing duration in the output string if the `ShowSecretsWarning` property is set to `true`.
* [`src/Common/AzurePSCmdlet.cs`]: Removed the debug log line that displayed the time taken by the sanitizer to process the object of the cmdlet. This change simplifies the output and removes potentially unnecessary information.
* [`src/Common/MetricHelper.cs`]: Updated the `ToString()` method to include the sanitizing duration in the …
> Add sanitize duration in the debug message and removed in EndProcessing

- src/Authentication.Abstractions/Models/ConfigKeysForCommon.cs
- src/Common/AzurePSCmdlet.cs
This pull request primarily focuses on the transition from using `DisableErrorRecordsPersistence` to `EnableErrorRecordsPersistence` in the `ConfigKeysForCommon` class and the `ShouldRecordDebugMessages` method. The changes are made to improve the code's readability and to make the feature opt-in rather than opt-out.
Key changes include:
* [`src/Authentication.Abstractions/Models/ConfigKeysForCommon.cs`](diffhunk://#diff-a0d7472a155c7177d7e58df9cd48b0f8613c6837e66ad5a6eed1b13f0a00dca0L32-L33): Removed the `DisableErrorRecordsPersistence` constant from the `ConfigKeysForCommon` class. The `EnableErrorRecordsPersistence` constant is now being used instead. This change is made to switch from an opt-out to an opt-in system for error record persistence.
* …
> opt-in error record config

- src/Authentication.Abstractions/Models/ConfigMetrics.cs
- src/Common/MetricHelper.cs
Change ConfigMetrics from Array to Dictionary, two benefits:
- We could check if this config is added in o(1) complexity. Previous design is o(n). A config could be read many times. In worst cases, List<ConfigMetrics> ConfigMetrics may contain same config info and exceed space limit
- We can define nickname for config. Take LoginExperienceV2 for instance, we can add 
ConfigMetrics.Add(ConfigKeys.LoginExperienceV2, new ConfigMetrics(ConfigKeys.LoginExperienceV2, "LoginExperienceVTwo", "On")) for telemetry as our database can't recognize number value in telemetry field.
-- no breaking change is introduced as ConfigMetrics is never used yey.
> Change ConfigMetrics from Array to Dictionary

- src/Common/AzurePSCmdlet.cs
- src/Common/Sanitizer/IOutputSanitizer.cs
Add IgnoredModules and IgnoredCmdlets to bypass unnecessary modules and/or cmdlets for secrets detection.
> Add new properties in the IOutputSanitizer

- src/Common/AzurePSCmdlet.cs
- src/Common/ColorAndFormat/PSStyle.cs
- Fix issue: https://github.com/Azure/azure-powershell/issues/24556
- Group in Azure-PowerShell PR: https://github.com/Azure/azure-powershell/pull/25735
- Current effect
- Changed effect
> Remove PSStyle if terminal does not support escape sequence

- src/Common/MetricHelper.cs
- src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
It's for `Content-AzAccount`. When it's run, the subscription id and tenant id is not set in context. That's why they are empty in telemetry.
This PR is going to set them before recording the telemetry.
> set subscription id and tenant id in telemetry if it's null

- src/Common/AzurePSCmdlet.cs
- src/Common/CmdletInfoHandler.cs
This PR is to set UserAgent for ARM request in case of SDK-based cmdlets.
And it fixes the bug of dumplicated CommandName and ParameterSetName.
> Set UserAgent for ARM telemetry

- src/Common/AzurePSCmdlet.cs
- src/Common/MetricHelper.cs
- src/Common/Sanitizer/SanitizerTelemetry.cs
This pull request includes several changes aimed at improving the handling and representation of detected properties in the sanitizer telemetry. The most important changes include the introduction of a new `DetectedPropertiesInfo` class, updates to the `SanitizerTelemetry` class to use this new class, and modifications to methods that interact with detected properties.
* **New `DetectedPropertiesInfo` Class**:
* Introduced `DetectedPropertiesInfo` to encapsulate detected properties and provide methods for adding and querying properties. (`src/Common/Sanitizer/SanitizerTelemetry.cs`, [src/Common/Sanitizer/SanitizerTelemetry.csR16-R91](diffhunk://#diff-f8410eb640aeb4660d721f15e982a3a77511ec4cdd1853677cab393f15e150edR16-R91))
* **Updates to `SanitizerTelemetry` Class**:
* Modified …
> Update telemetry data to add moniker of the detected properties

- src/Authentication.Abstractions/AzureSession.cs
Fix Azure/azure-powershell#26624
This pull request Improved the `AzureSession.TryGetComponent` method to use `TryGetValue` instead of `ContainsKey` plus `[]` to avoid potential race condition between the two operations.
> fix race condition in dictionary operations

- src/Authentication.Abstractions.Test/AzureSessionTest.cs
- src/Authentication.Abstractions/AzureSession.cs
- In the method `RegisterComponent`, the operation that checks key existance ` _componentRegistry.TryGetValue(key, out var existed)`and the operation that updates the value of the key `_componentRegistry[key] = component` are not atomic.  The result is the when you want to register the components with the same key in different threads in no-overwrite mode,  the component is actually overwritten. What you can see is that with the unfixed codes, the result of the test case `TestComponentRegistrationSameComponentNoOverwritten` is unpredictable.
> Fix concurrency issue of Component Registery of Azure Session

- src/Storage.Management/Storage.Management.csproj
- src/Storage/Storage.csproj
This PR removes the attribute <OmitJsonPackage> to forcefully use the same Newtonsoft.Json among all projects defined in the Dependencies.targets.
> Force using the same Newtonsoft.Json version for all projects.

- src/Authentication.Abstractions/Interfaces/IAuthenticationFactory.cs
Add a new interface of "RemoveUser" to accept authority as the input for Authority from environment is required to decide whether public client should be created with broker or not.
> Fix that RemoveUser Doesn't Work When Create Public Client with Broker

- src/Common/ColorAndFormat/PSStyle.cs
https://github.com/Azure/azure-powershell/issues/26155
Accessing `host?.UI?.SupportsVirtualTerminal` in automation runbooks can cause NullReferenceException. This PR handles the exception and defaults styling to be disabled.
> Handles NullRefEx of PSStyle in automation runbooks

- src/Authentication.Abstractions/AzureEnvironment.BuiltIn.cs
- src/Authentication.Abstractions/AzureEnvironment.cs
- src/Authentication.Abstractions/AzureEnvironmentConstants.cs
- src/Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs
To enable updating the auth scope, this PR adds it to the environment. There will be a follow-up PR to update `Set-AzEnvironment` and logic in `SshCredentialFactory` in azure-powershell repo.
> Added SSH auth scope to environment
